---
- name: Install Amazon Corretto 17
  dnf:
    name: java-17-amazon-corretto-devel
    state: present

- name: Create tomcat group
  group:
    name: tomcat
    state: present

- name: Create tomcat user
  user:
    name: tomcat
    group: tomcat
    home: /usr/share/tomcat
    create_home: no
    shell: /bin/false

- name: Download and Extract Tomcat 9
  unarchive:
    src: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.98/bin/apache-tomcat-9.0.98.tar.gz
    dest: /opt/
    remote_src: yes
    owner: tomcat
    group: tomcat
    creates: /opt/apache-tomcat-9.0.98/bin/startup.sh

- name: Symlink Tomcat directory
  file:
    src: /opt/apache-tomcat-9.0.98
    path: /usr/share/tomcat
    state: link
    owner: tomcat
    group: tomcat

- name: Configure Tomcat server and users
  template:
    src: "{{ item.src }}"
    dest: "/usr/share/tomcat/conf/{{ item.dest }}"
    owner: tomcat
    group: tomcat
  loop:
    - { src: 'server.xml.j2', dest: 'server.xml' }
    - { src: 'tomcat-users.xml.j2', dest: 'tomcat-users.xml' }
  notify: restart tomcat

- name: Install Systemd Unit File
  copy:
    dest: /etc/systemd/system/tomcat.service
    content: |
      [Unit]
      Description=Apache Tomcat 9 Web Application Container
      After=network.target

      [Service]
      Type=forking
      User=tomcat
      Group=tomcat
      
      # Use the absolute path to ensure no version confusion
      Environment="JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto.x86_64"
      Environment="CATALINA_PID=/usr/share/tomcat/temp/tomcat.pid"
      Environment="CATALINA_HOME=/usr/share/tomcat"
      Environment="CATALINA_BASE=/usr/share/tomcat"
      # Adding extra memory parameters can help avoid silent startup crashes
      Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"

      ExecStart=/usr/share/tomcat/bin/startup.sh
      ExecStop=/usr/share/tomcat/bin/shutdown.sh

      [Install]
      WantedBy=multi-user.target

- name: Start and Enable Tomcat
  systemd:
    name: tomcat
    state: started
    enabled: yes
    daemon_reload: yes

- name: Wait for tomcat to start
  wait_for:
    port: "{{ http_port | default(8080) }}"
    delay: 5
    timeout: 60
