- name: Install Amazon Corretto 17
  dnf:
    name: java-17-amazon-corretto-devel
    state: present

- name: Download Jenkins repository file
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    mode: '0644'

- name: Import Jenkins GPG Key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

- name: Install Jenkins
  dnf:
    name: jenkins
    state: latest

- name: Ensure Jenkins directories have correct ownership
  file:
    path: "{{ item }}"
    owner: jenkins
    group: jenkins
    state: directory
    recurse: yes
  loop:
    - /var/lib/jenkins
    - /var/cache/jenkins
    - /var/log/jenkins

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Restart Jenkins service
  systemd:
    name: jenkins
    state: restarted
    enabled: yes
