- name: Create AWS VPC and related network components
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Pip installation
      yum:
        name:
          - python3-pip
          - python3-devel
        state: present

    - name: Ensure Python dependencies are installed
      pip:
        name:
          - boto3
          - botocore
        executable: pip3
        state: present 

    - name: Create a new VPC
      amazon.aws.ec2_vpc_net:
        name: my-ansible-vpc
        cidr_block: "10.0.0.0/16"
        region: "us-east-1"
        dns_hostnames: true
        dns_support: true
        state: present
      register: vpc_output
      # The 'register' keyword saves the module's output to a variable 
      # for use in subsequent tasks (e.g., getting the new VPC ID).

    - name: Display VPC ID
      debug:
        msg: "The newly created VPC ID is {{ vpc_output.vpc.id }}"
